import { Inter, Outfit } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
// https://dashboard.clerk.com/apps/app_2kabGZKMCFBWT7yAppQulMnUxIT/instances/ins_2kabGXM2IPocoA60LUBLodaZPRV

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // cleark login
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
      {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
